apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastfood-app
  template:
    metadata:
      labels:
        app: fastfood-app
    spec:
      containers:
      - name: fastfood-app
        image: antoniodsaf/fiap-fastfood:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: configmap-fastfood
