apiVersion: v1
kind: Service
metadata:
  name: svc-db-fastfood
  labels:
    app: postgres
spec:
  type: NodePort
  #type: ClusterIP
  ports:
    - port: 5432
      #targetPort: 5432
  selector:
    app: postgres