apiVersion: v1
kind: Service
metadata:
  name: svc-fastfood
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-name: "fastfood-lb"
spec:
  type: LoadBalancer
  ports:
    - port: 3000
  selector:
    app: fastfood-app